# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy>=1.24", "scipy>=1.10"]
# ///
"""
BEARS FANTASY LAND - 45 s brand-story score, synthesized from scratch.

Every sound in this file is generated by code (additive / subtractive / noise
synthesis). No samples, soundfonts or third-party audio are used, so the
copyright of the output belongs entirely to the owner of this script.

Run (one command, from this folder):
    uv run compose.py            # needs ffmpeg on PATH for the MP3
    python compose.py            # if numpy + scipy are already installed

Outputs (next to this file):
    bears-brand-score-45s.wav    48 kHz / 32-bit float / stereo, exactly 45.000 s
    bears-brand-score-45s.mp3    320 kbps
    brand-score-markers.json     event times exported from the score itself

Timing contract: brand-structure.json (96 BPM, 4/4, bar = 2.5 s, 18 bars).
At 48 kHz one beat is exactly 30000 samples, so every grid event is placed
on an exact integer sample.
"""
from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import sys
import time

import numpy as np
from scipy.io import wavfile
from scipy.ndimage import minimum_filter1d, uniform_filter1d
from scipy.signal import butter, fftconvolve, istft, resample_poly, sosfilt, stft

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = 20261006
SR = 48000
BPM = 96
BEAT = 60.0 / BPM            # 0.625 s
BAR = 4 * BEAT               # 2.5 s
DUR = 45.0
N = int(round(DUR * SR))     # 2_160_000
TAIL = 6 * SR                # render headroom, trimmed at the end
NT = N + TAIL
DROP = 30.0
PRE_HIT = 28.75
GATE_FROM, GATE_TO = 28.84, 28.90   # pre-drop vacuum (reverb tails cut)
TWO_PI = 2.0 * np.pi

with open(os.path.join(HERE, "brand-structure.json"), encoding="utf-8") as fh:
    CONTRACT = json.load(fh)
assert abs(CONTRACT["bar"] - BAR) < 1e-9 and CONTRACT["bpm"] == BPM
assert CONTRACT["duration"] == DUR


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def T(bar: int, beat: float = 1.0) -> float:
    """Contract time of (bar, beat), both 1-based."""
    return (bar - 1) * BAR + (beat - 1) * BEAT


def S(t: float) -> int:
    return int(round(t * SR))


_PC = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def M(name: str) -> int:
    """'F#4' -> MIDI number."""
    pc = _PC[name[0]]
    i = 1
    while i < len(name) and name[i] in "#b":
        pc += 1 if name[i] == "#" else -1
        i += 1
    return 12 * (int(name[i:]) + 1) + pc


def mtof(m: float) -> float:
    return 440.0 * 2.0 ** ((m - 69) / 12.0)


def rng_for(*key) -> np.random.Generator:
    h = SEED
    for k in key:
        for ch in str(k):
            h = (h * 131 + ord(ch)) % (2**61 - 1)
    return np.random.default_rng(h)


def pan_gains(p: float):
    a = (np.clip(p, -1, 1) + 1) * np.pi / 4
    return math.cos(a) * math.sqrt(2) * 0.5 + 0.0, math.sin(a) * math.sqrt(2) * 0.5


def smoothstep(x):
    x = np.clip(x, 0.0, 1.0)
    return x * x * (3 - 2 * x)


def fade_edges(x, fin=0.002, fout=0.02):
    """Click-free start/end (raised cosine), in place, works on (..., L)."""
    L = x.shape[-1]
    a = min(int(fin * SR), L // 2)
    b = min(int(fout * SR), L // 2)
    if a > 0:
        x[..., :a] *= 0.5 - 0.5 * np.cos(np.pi * np.arange(a) / a)
    if b > 0:
        x[..., L - b:] *= 0.5 + 0.5 * np.cos(np.pi * np.arange(b) / b)
    return x


def lp(fc, order=2):
    return butter(order, min(fc, SR * 0.45) / (SR / 2), "low", output="sos")


def hp(fc, order=2):
    return butter(order, fc / (SR / 2), "high", output="sos")


def bp(f1, f2, order=2):
    return butter(order, [f1 / (SR / 2), min(f2, SR * 0.45) / (SR / 2)], "band", output="sos")


def peaking(f0, q, gain_db):
    """RBJ cookbook peaking EQ as one SOS section."""
    A = 10 ** (gain_db / 40)
    w = TWO_PI * f0 / SR
    al = math.sin(w) / (2 * q)
    b = [1 + al * A, -2 * math.cos(w), 1 - al * A]
    a = [1 + al / A, -2 * math.cos(w), 1 - al / A]
    return np.array([[b[0] / a[0], b[1] / a[0], b[2] / a[0], 1.0, a[1] / a[0], a[2] / a[0]]])


def shelf(f0, gain_db, kind="low", s=0.8):
    A = 10 ** (gain_db / 40)
    w = TWO_PI * f0 / SR
    al = math.sin(w) / 2 * math.sqrt((A + 1 / A) * (1 / s - 1) + 2)
    c = math.cos(w)
    if kind == "low":
        b0 = A * ((A + 1) - (A - 1) * c + 2 * math.sqrt(A) * al)
        b1 = 2 * A * ((A - 1) - (A + 1) * c)
        b2 = A * ((A + 1) - (A - 1) * c - 2 * math.sqrt(A) * al)
        a0 = (A + 1) + (A - 1) * c + 2 * math.sqrt(A) * al
        a1 = -2 * ((A - 1) + (A + 1) * c)
        a2 = (A + 1) + (A - 1) * c - 2 * math.sqrt(A) * al
    else:
        b0 = A * ((A + 1) + (A - 1) * c + 2 * math.sqrt(A) * al)
        b1 = -2 * A * ((A - 1) + (A + 1) * c)
        b2 = A * ((A + 1) + (A - 1) * c - 2 * math.sqrt(A) * al)
        a0 = (A + 1) - (A - 1) * c + 2 * math.sqrt(A) * al
        a1 = 2 * ((A - 1) - (A + 1) * c)
        a2 = (A + 1) - (A - 1) * c - 2 * math.sqrt(A) * al
    return np.array([[b0 / a0, b1 / a0, b2 / a0, 1.0, a1 / a0, a2 / a0]])


def filt(sos, x):
    return sosfilt(sos, x, axis=-1)


def polyblep_saw(freq, phase0=0.0):
    """Band-limited sawtooth (PolyBLEP) for a per-sample frequency array."""
    dt = np.asarray(freq, dtype=np.float64) / SR
    ph = (phase0 + np.cumsum(dt)) % 1.0
    y = 2.0 * ph - 1.0
    m = ph < dt
    t = ph[m] / dt[m]
    y[m] -= t + t - t * t - 1.0
    m = ph > 1.0 - dt
    t = (ph[m] - 1.0) / dt[m]
    y[m] -= t * t + t + t + 1.0
    return y


# --------------------------------------------------------------------------
# mixer
# --------------------------------------------------------------------------
BUSES = ["piano", "strings", "pad", "brass", "bass", "perc", "impact", "fx", "pluck"]
bus = {k: np.zeros((2, NT)) for k in BUSES}
EVENTS: list[dict] = []


def add(name, t0, sig, p=0.0, gain=1.0):
    """Add a mono (L,) or stereo (2,L) signal to a bus at time t0 (s)."""
    s0 = S(t0)
    if sig.ndim == 1:
        gl, gr = pan_gains(p)
        sig = np.vstack([sig * gl, sig * gr])
    L = sig.shape[1]
    if s0 < 0:
        sig = sig[:, -s0:]
        L += s0
        s0 = 0
    e = min(NT, s0 + L)
    bus[name][:, s0:e] += gain * sig[:, : e - s0]


def event(kind, t, **kw):
    d = {"t": round(float(t), 6), "sample": S(t), "type": kind}
    d.update(kw)
    EVENTS.append(d)


# --------------------------------------------------------------------------
# harmony (voicings hand-written for smooth, parallel-free voice leading)
# --------------------------------------------------------------------------
V = {
    "D":    ("D2",  ["F#3", "A3", "D4"]),
    "A/C#": ("C#2", ["E3", "A3", "E4"]),
    "Bm":   ("B1",  ["F#3", "B3", "D4"]),
    "Bm*":  ("B1",  ["D3", "F#3", "B3"]),   # low voicing used in the build
    "G":    ("G1",  ["G3", "B3", "D4"]),
    "A":    ("A1",  ["E3", "A3", "C#4"]),
}
PCS = {"D": {2, 6, 9}, "A/C#": {9, 1, 4}, "A": {9, 1, 4}, "Bm": {11, 2, 6},
       "Bm*": {11, 2, 6}, "G": {7, 11, 2}}
# (bar, beat, chord)
PROG = [(1, 1, "D"), (2, 1, "A/C#"), (3, 1, "Bm"), (4, 1, "G"),
        (5, 1, "Bm"), (6, 1, "G"), (7, 1, "D"), (8, 1, "A"),
        (9, 1, "G"), (10, 1, "A"), (11, 1, "Bm*"), (12, 1, "A/C#"),
        (13, 1, "D"), (14, 1, "A/C#"), (15, 1, "Bm"), (16, 1, "G"), (16, 3, "A"),
        (17, 1, "D"), (18, 1, "D")]
SEGS = []  # (t_start, t_end, chord)
for i, (b, bt, c) in enumerate(PROG):
    t0 = T(b, bt)
    t1 = T(*PROG[i + 1][:2]) if i + 1 < len(PROG) else DUR
    SEGS.append((t0, t1, c))


def chord_at(t):
    for t0, t1, c in SEGS:
        if t0 <= t + 1e-9 < t1:
            return c
    return SEGS[-1][2]


def check_voice_leading():
    """Report parallel perfect 5ths / octaves between any two voices."""
    seq = [c for _, _, c in SEGS]
    problems = []
    for a, b in zip(seq, seq[1:]):
        if a == b:
            continue
        va = [M(V[a][0])] + [M(x) for x in V[a][1]]
        vb = [M(V[b][0])] + [M(x) for x in V[b][1]]
        for i in range(4):
            for j in range(i + 1, 4):
                ia, ib = (va[j] - va[i]) % 12, (vb[j] - vb[i]) % 12
                moved = va[i] != vb[i] or va[j] != vb[j]
                same_dir = np.sign(vb[i] - va[i]) == np.sign(vb[j] - va[j]) != 0
                if moved and same_dir and ia == ib and ia in (0, 7):
                    problems.append(f"{a}->{b} voices {i},{j} parallel {'8ve' if ia == 0 else '5th'}")
    return problems


# --------------------------------------------------------------------------
# melody (bar, beat, beats, note) - the 4-bar theme + verse answer
# --------------------------------------------------------------------------
THEME = [
    (1, 1, 1, "A4"), (1, 2, 1.5, "F#5"), (1, 3.5, .5, "E5"), (1, 4, 1, "D5"),
    (2, 1, 1, "A4"), (2, 2, 1.5, "E5"), (2, 3.5, .5, "D5"), (2, 4, 1, "C#5"),
    (3, 1, 1, "F#4"), (3, 2, 1.5, "D5"), (3, 3.5, .5, "C#5"), (3, 4, 1, "B4"),
    (4, 1, 1.5, "B4"), (4, 2.5, .5, "A4"), (4, 3, 1, "G4"), (4, 4, 1, "A4"),
]
VERSE = [
    (5, 1, 1, "B4"), (5, 2, 1.5, "F#5"), (5, 3.5, .5, "E5"), (5, 4, 1, "D5"),
    (6, 1, 1, "G4"), (6, 2, 1.5, "D5"), (6, 3.5, .5, "C#5"), (6, 4, 1, "B4"),
    (7, 1, 1, "A4"), (7, 2, 1.5, "F#5"), (7, 3.5, .5, "G5"), (7, 4, 1, "A5"),
    (8, 1, 1.5, "G5"), (8, 2.5, .5, "F#5"), (8, 3, 2, "E5"),
]
# climax = theme shifted by 12 bars; last bar re-harmonised as a cadence turn
CLIMAX = [(b + 12, bt, d, n) for (b, bt, d, n) in THEME[:12]] + [
    (16, 1, 1.5, "B4"), (16, 2.5, .5, "A4"), (16, 3, 1, "C#5"), (16, 4, 1, "E5"),
]


# --------------------------------------------------------------------------
# instruments
# --------------------------------------------------------------------------
def piano_note(midi, vel, hold, rng):
    """Felt piano: inharmonic partials, two detuned strings, per-partial
    two-stage decay, velocity-dependent brightness, felt hammer thump."""
    f0 = mtof(midi)
    tau0 = float(np.clip(7.5 * 2 ** (-(midi - 45) / 15.0), 0.9, 9.0))
    L = int(SR * min(hold + 0.45, 5.0 * tau0 + 0.3))
    t = np.arange(L) / SR
    B = 0.00007 * 2 ** ((midi - 40) / 13.0)          # inharmonicity
    fc = 650 + 3600 * vel ** 1.8                      # felt brightness
    hpos = 0.115 + 0.02 * rng.random()                # hammer position
    det = 2 ** ((0.35 + 0.9 * rng.random()) / 1200)  # unison detune
    out = np.zeros((2, L))
    for n in range(1, 60):
        fn = n * f0 * math.sqrt(1 + B * n * n)
        if fn > 14000 or fn > fc * 5:
            break
        a = n ** -1.05 * math.exp(-((fn / fc) ** 1.35)) * (0.22 + abs(math.sin(math.pi * n * hpos)))
        if a < 3e-4:
            continue
        tau = tau0 / (1 + 0.09 * (n - 1)) / (1 + (fn / 2600) ** 1.25)
        env = 0.58 * np.exp(-t / (tau * 0.2)) + 0.42 * np.exp(-t / tau)
        p1, p2 = rng.random(2) * TWO_PI
        s1 = np.sin(TWO_PI * fn * t + p1)
        s2 = np.sin(TWO_PI * fn * det * t + p2)
        out[0] += a * env * (0.6 * s1 + 0.4 * s2)
        out[1] += a * env * (0.4 * s1 + 0.6 * s2)
    # attack: felt hammer contact time (softer = slower)
    att = int(SR * (0.0015 + 0.003 * (1 - vel)))
    out[:, :att] *= np.sin(0.5 * np.pi * np.arange(att) / att) ** 2
    # felt thump + soundboard knock
    nl = min(L, int(0.09 * SR))
    tn = np.arange(nl) / SR
    nz = filt(lp(220 + 1600 * vel), rng.standard_normal(nl)) * np.exp(-tn / 0.011)
    knock = np.sin(TWO_PI * (88 + 30 * rng.random()) * tn) * np.exp(-tn / 0.03)
    thump = (0.10 * nz + 0.035 * knock) * vel
    thump[: int(0.0015 * SR)] *= np.linspace(0, 1, int(0.0015 * SR))
    out[:, :nl] += thump
    # damper (felt, a little slow) after the hold time
    if hold < L / SR:
        h = S(hold)
        out[:, h:] *= np.exp(-np.arange(L - h) / SR / 0.085)
    out *= (0.18 + 0.82 * vel ** 1.45) * 0.22
    return fade_edges(out, 0.0, 0.03)


def piano(t0, name_or_midi, vel, hold, tag="pn", record=None):
    midi = M(name_or_midi) if isinstance(name_or_midi, str) else name_or_midi
    rng = rng_for(tag, round(t0 * 1000), midi)
    sig = piano_note(midi, vel, hold, rng)
    w = float(np.clip((midi - 62) / 30.0, -0.45, 0.45))   # player's perspective
    gl, gr = pan_gains(w)
    sig[0] *= gl * 1.4142
    sig[1] *= gr * 1.4142
    add("piano", t0, sig)
    if record:
        event(record[0], t0, note=name_or_midi if isinstance(name_or_midi, str) else midi, **record[1])


SECTIONS = {
    #       voices spread(c) vib(c) pan  width  hp   lp dark/bright   body EQ
    "vln1": (6, 9.0, 13.0, -0.48, 0.30, 190, (2000, 3800), [(420, 1.2, 2.5), (3100, 1.6, -4.0)]),
    "vln2": (6, 8.0, 12.0, -0.22, 0.30, 170, (1800, 3400), [(420, 1.2, 2.0), (3100, 1.6, -4.0)]),
    "vla":  (5, 7.0, 10.0, 0.18, 0.28, 120, (1500, 2800), [(380, 1.2, 2.0), (2600, 1.6, -3.0)]),
    "vc":   (5, 6.0, 9.0, 0.40, 0.25, 55, (1100, 2300), [(220, 1.1, 2.5), (2400, 1.5, -3.0)]),
    "cb":   (4, 5.0, 6.0, 0.22, 0.15, 28, (520, 1000), [(110, 1.0, 2.0)]),
}


def string_note(sec, midi, dur, vel, att, rel, rng):
    nv, spread, vib, p, width, hpf, (fd, fb), body = SECTIONS[sec]
    f0 = mtof(midi)
    L = int((dur + rel + 0.05) * SR)
    t = np.arange(L) / SR
    out = np.zeros((2, L))
    for v in range(nv):
        x = (v / (nv - 1)) * 2 - 1
        cents = x * spread + rng.normal(0, 1.2)
        rate = rng.uniform(4.7, 5.8)
        depth = vib * rng.uniform(0.7, 1.15) * smoothstep((t - rng.uniform(0.25, 0.45)) / 0.7)
        drift = 2.0 * np.sin(TWO_PI * rng.uniform(0.07, 0.3) * t + rng.random() * 6.3) \
            + 1.2 * np.sin(TWO_PI * rng.uniform(0.3, 0.8) * t + rng.random() * 6.3)
        c = cents + depth * np.sin(TWO_PI * rate * t + rng.random() * 6.3) + drift
        saw = polyblep_saw(f0 * 2 ** (c / 1200), rng.random())
        gl, gr = pan_gains(p + width * x * 0.5)
        out[0] += saw * gl
        out[1] += saw * gr
    out /= math.sqrt(nv)
    # amplitude envelope: slow bow attack, gentle swell, smooth release
    a = smoothstep(t / att) ** 0.8
    r = 0.5 + 0.5 * np.cos(np.pi * np.clip((t - dur) / rel, 0, 1))
    env = a * r * (1 + 0.08 * smoothstep((t - att) / max(dur - att, 0.1)))
    # dynamic brightness: crossfade dark/bright low-pass by envelope*velocity
    dark = filt(lp(fd, 4), out)
    bright = filt(lp(fb, 4), out)
    k = np.clip(env * (0.25 + 0.75 * vel), 0, 1)
    y = dark + (bright - dark) * k
    # bow hair noise: band-limited, follows the bow pressure (stronger on attack)
    bow = filt(bp(f0 * 2.5, min(f0 * 9, 3000)), rng.standard_normal((2, L)))
    y += bow * (0.05 + 0.10 * np.exp(-t / 0.12)) * (0.4 + 0.6 * vel)
    for (f, q, g) in body:
        y = filt(peaking(f, q, g), y)
    y = filt(hp(hpf), y)
    return fade_edges(y * env * vel, 0.003, 0.03)


def strings(sec, t0, name, dur, vel, att=0.45, rel=0.7, gain=1.0):
    midi = M(name) if isinstance(name, str) else name
    rng = rng_for(sec, round(t0 * 1000), midi)
    add("strings", t0, string_note(sec, midi, dur, vel, att, rel, rng), gain=gain)


def pad_note(midi, dur, vel, rng, att=1.6, rel=1.8, cutoff=950):
    f0 = mtof(midi)
    L = int((dur + rel + 0.05) * SR)
    t = np.arange(L) / SR
    out = np.zeros((2, L))
    for v in range(4):
        x = (v / 3) * 2 - 1
        c = x * 11 + 3 * np.sin(TWO_PI * rng.uniform(0.1, 0.25) * t + rng.random() * 6.3)
        saw = polyblep_saw(f0 * 2 ** (c / 1200), rng.random())
        gl, gr = pan_gains(x * 0.7)
        out[0] += saw * gl
        out[1] += saw * gr
    tri = np.abs(((np.arange(L) * f0 / SR) % 1.0) * 4 - 2) - 1   # soft fundamental
    out += 0.35 * tri
    out = filt(lp(cutoff, 4), out) * 0.5
    # breathy air layer (kept low and below the harsh band)
    air = filt(bp(700, 2200), rng.standard_normal((2, L))) * 0.05
    air *= 0.6 + 0.4 * np.sin(TWO_PI * 0.23 * t + rng.random() * 6)
    out += air
    env = smoothstep(t / att) * (0.5 + 0.5 * np.cos(np.pi * np.clip((t - dur) / rel, 0, 1)))
    return fade_edges(filt(hp(110), out) * env * vel, 0.01, 0.05)


def pad(t0, name, dur, vel, **kw):
    midi = M(name)
    add("pad", t0, pad_note(midi, dur, vel, rng_for("pad", round(t0 * 1000), midi), **kw))


def brass_note(midi, dur, vel, rng, att=0.22, rel=0.7):
    """Low brass pad: drive saws, swelling low-pass, vowel-like formants."""
    f0 = mtof(midi)
    L = int((dur + rel + 0.05) * SR)
    t = np.arange(L) / SR
    x = np.zeros(L)
    for v in range(3):
        c = (v - 1) * 4.5 + 2.5 * np.sin(TWO_PI * rng.uniform(0.15, 0.4) * t + rng.random() * 6)
        x += polyblep_saw(f0 * 2 ** (c / 1200), rng.random())
    x = np.tanh(1.6 * x / 3) / np.tanh(1.6)
    blat = 0.35 + 0.65 * (1 - np.exp(-t / 0.28))
    dark, bright = filt(lp(380, 4), x), filt(lp(1900, 4), x)
    y = dark + (bright - dark) * (blat * vel)
    y = filt(peaking(520, 1.4, 6.0), y)
    y = filt(peaking(1150, 2.2, 3.5), y)
    y = filt(peaking(2600, 1.5, -5.0), y)
    y = filt(hp(65), y)
    env = smoothstep(t / att) * (0.5 + 0.5 * np.cos(np.pi * np.clip((t - dur) / rel, 0, 1)))
    return fade_edges(y * env * vel, 0.004, 0.04)


def brass(t0, name, dur, vel, p=0.0):
    midi = M(name)
    add("brass", t0, brass_note(midi, dur, vel, rng_for("br", round(t0 * 1000), midi)), p=p)


def pizz_note(midi, vel, rng):
    f0 = mtof(midi)
    L = int(1.4 * SR)
    t = np.arange(L) / SR
    y = np.zeros(L)
    for n in range(1, 24):
        fn = n * f0 * (1 + 0.0004 * n * n)
        if fn > 7000:
            break
        a = n ** -1.25 * math.exp(-fn / (1400 + 2200 * vel))
        tau = 0.42 / (1 + 0.28 * (n - 1))
        y += a * np.exp(-t / tau) * np.sin(TWO_PI * fn * t + rng.random() * 0.4)
    y[: int(0.0012 * SR)] *= np.linspace(0, 1, int(0.0012 * SR))
    y = filt(peaking(300, 1.2, 4.0), y)
    y = filt(hp(90), y)
    return fade_edges(y * vel * 0.35, 0.0, 0.05)


def sub_note(midi, dur, vel, att=0.006, decay=0.6, sustain=0.45, rel=0.12):
    f0 = mtof(midi)
    while f0 < 38:
        f0 *= 2
    L = int((dur + rel) * SR)
    t = np.arange(L) / SR
    x = np.sin(TWO_PI * f0 * t)
    x = np.tanh(1.4 * x) / np.tanh(1.4)           # warm 3rd harmonic
    x += 0.18 * np.sin(TWO_PI * 2 * f0 * t)        # gentle 2nd for small speakers
    env = smoothstep(t / att) * (sustain + (1 - sustain) * np.exp(-t / decay))
    env *= 0.5 + 0.5 * np.cos(np.pi * np.clip((t - dur) / rel, 0, 1))
    return fade_edges(x * env * vel, 0.0, 0.01)


def sub(t0, name, dur, vel, **kw):
    add("bass", t0, sub_note(M(name), dur, vel, **kw))


def drum(vel, pitch, size, rng, slap=1.0):
    """Taiko / tom: swept sine body + membrane modes + stick slap + thud."""
    L = int((0.9 + 0.9 * size) * SR)
    t = np.arange(L) / SR
    fe = 60.0 * pitch
    f = fe + (fe * 1.25) * np.exp(-t / 0.022)
    body = np.sin(TWO_PI * np.cumsum(f) / SR) * np.exp(-t / (0.38 * size))
    modes = np.zeros(L)
    for r, a, d in zip([1.59, 2.14, 2.30, 2.65, 2.92, 3.16, 3.50],
                       [.45, .32, .26, .2, .15, .11, .08],
                       [.2, .15, .13, .1, .085, .075, .06]):
        fm = fe * r * (1 + 0.04 * np.exp(-t / 0.03))
        modes += a * np.sin(TWO_PI * np.cumsum(fm) / SR) * np.exp(-t / (d * size))
    nl = int(0.12 * SR)
    tn = np.arange(nl) / SR
    sl = filt(bp(500, 3200), rng.standard_normal(nl)) * np.exp(-tn / 0.005) * 0.55 * slap
    th = filt(lp(160), rng.standard_normal(nl)) * np.exp(-tn / 0.045) * 2.5
    x = body + 0.6 * modes
    x[:nl] += sl + th
    x = np.tanh(1.5 * x * vel) / np.tanh(1.5)
    x[: int(0.0004 * SR)] *= np.linspace(0, 1, int(0.0004 * SR))
    return fade_edges(x, 0.0, 0.05)


def DP(note):
    """Drum pitch factor that tunes the drum body (60 Hz * factor) to a note."""
    return mtof(M(note)) / 60.0


def hit(t0, kind, vel, pitch, size, p=0.0, gain=1.0, slap=1.3):
    rng = rng_for("drum", round(t0 * 1000), kind)
    add("perc", t0, drum(vel, pitch, size, rng, slap), p=p, gain=gain)
    event(kind, t0, vel=round(vel, 3))


def cymbal(L_sec, rng, decay=1.8):
    L = int(L_sec * SR)
    t = np.arange(L) / SR
    nz = rng.standard_normal((2, L))
    wash = filt(lp(10500, 2), filt(hp(3200, 2), nz)) * np.exp(-t / decay)
    body = filt(bp(700, 2400), nz[::-1]) * np.exp(-t / (decay * 0.35)) * 0.35
    shimmer = np.zeros((2, L))
    for _ in range(70):
        f = math.exp(rng.uniform(math.log(2200), math.log(8500)))
        a = rng.uniform(0.2, 1.0) * 0.012
        d = rng.uniform(0.5, 1.0) * decay
        ch = rng.integers(0, 2)
        shimmer[ch] += a * np.sin(TWO_PI * f * t + rng.random() * 6.3) * np.exp(-t / d)
    y = wash + body + shimmer
    y[:, : int(0.001 * SR)] *= np.linspace(0, 1, int(0.001 * SR))
    return fade_edges(y, 0.0, 0.05)


def impact_sig(size, rng, root_hz=None):
    """Cinematic impact: sub drop + boom + multiband noise burst + metal tail."""
    L = int(5.0 * SR)
    t = np.arange(L) / SR
    root_hz = root_hz or mtof(M("D2"))
    f_end = root_hz / 2 if root_hz / 2 >= 34 else root_hz   # land on the bass note (>= 34 Hz)
    f = f_end + 45 * np.exp(-t / 0.32)
    subd = np.sin(TWO_PI * np.cumsum(f) / SR) * np.exp(-t / (0.9 * size)) * 0.9
    boom = np.zeros(L)
    b = drum(1.0, root_hz / 60.0, 1.7 * size, rng, slap=0.9)
    boom[: len(b)] = b
    nz = rng.standard_normal((2, L))
    burst = (filt(hp(2200), nz) * np.exp(-t / 0.05) * 0.25
             + filt(bp(250, 2200), nz) * np.exp(-t / 0.17) * 0.55
             + filt(lp(260), nz) * np.exp(-t / 0.45) * 0.9)
    metal = np.zeros((2, L))
    for _ in range(34):
        fr = math.exp(rng.uniform(math.log(240), math.log(3400)))
        a = rng.uniform(0.3, 1.0) * 0.05 / math.sqrt(fr / 240)
        d = rng.uniform(1.0, 2.8) * size
        pan = rng.uniform(-1, 1)
        s = a * np.sin(TWO_PI * fr * (t - 0.004 * t * t) + rng.random() * 6.3) * np.exp(-t / d)
        s *= smoothstep(t / 0.012)
        metal[0] += s * (1 - pan) * 0.5
        metal[1] += s * (1 + pan) * 0.5
    mono = subd + 0.9 * boom
    y = np.vstack([mono, mono]) + burst + metal
    y = np.tanh(1.2 * y) / np.tanh(1.2)
    y[:, : int(0.0005 * SR)] *= np.linspace(0, 1, int(0.0005 * SR))
    return fade_edges(y, 0.0, 0.2)


def bass_hz(t):
    """Bass note of the chord sounding at t, folded into 45-90 Hz (drum tuning)."""
    f = mtof(M(V[chord_at(t)][0]))
    while f < 45:
        f *= 2
    while f > 90:
        f /= 2
    return f


def impact(t0, kind, size=1.0, gain=1.0):
    sig = impact_sig(size, rng_for("imp", round(t0 * 1000)), bass_hz(t0 + 0.01))
    add("impact", t0, sig, gain=gain)
    event(kind, t0, size=size)


def stft_filter(x, gain_fn, nper=2048, hop=256):
    _, tt, Z = stft(x, fs=SR, nperseg=nper, noverlap=nper - hop)
    ff = np.fft.rfftfreq(nper, 1 / SR)
    G = gain_fn(ff[:, None], tt[None, :])
    _, y = istft(Z * G, fs=SR, nperseg=nper, noverlap=nper - hop)
    return y[..., : x.shape[-1]]


def riser_sig(length, rng):
    L = int(length * SR)
    nz = rng.standard_normal((2, L))

    def g(f, tt):
        u = np.clip(tt / length, 0, 1)
        fc = 350 * (24 ** (u ** 1.4))                   # 350 Hz -> 8.4 kHz
        oc = np.log2(np.maximum(f, 20) / fc)
        return np.exp(-0.5 * (oc / 0.75) ** 2) + 0.04 * (f < 9000)

    y = stft_filter(nz, g)
    t = np.arange(L) / SR
    u = t / length
    trem = 1 - 0.06 * (0.5 + 0.5 * np.sin(TWO_PI * np.cumsum(3 + 11 * u ** 2) / SR))
    y *= (u ** 2.3) * trem
    y = filt(lp(11000, 4), y)
    return fade_edges(y, 0.05, 0.002)


# --------------------------------------------------------------------------
# reverb: decorrelated stereo noise IR, band-dependent decay + early reflections
# --------------------------------------------------------------------------
def make_ir(rt, length, predelay, rng, n_er=14, er_span=0.07):
    L = int(length * SR)
    t = np.arange(L) / SR
    bands = [(20, 180, 1.15), (180, 500, 1.05), (500, 1200, 1.0), (1200, 2800, 0.85),
             (2800, 6000, 0.62), (6000, 12000, 0.42), (12000, 20000, 0.25)]
    ir = np.zeros((2, L))
    for ch in range(2):
        nz = rng.standard_normal(L)
        for lo, hi, k in bands:
            if lo <= 20:
                band = filt(lp(hi, 4), nz)
            elif hi >= 20000:
                band = filt(hp(lo, 4), nz)
            else:
                band = filt(bp(lo, hi, 2), nz)
            ir[ch] += band * np.exp(-6.9078 * t / (rt * k))
    ir *= smoothstep((t - predelay) / 0.03)          # late field fades in
    ir /= np.sqrt(np.sum(ir ** 2) / 2)
    # early reflections (sparse taps, alternating sides, slightly darkened)
    er = np.zeros((2, L))
    for i in range(n_er):
        d = predelay * 0.4 + rng.uniform(0.004, er_span)
        a = 0.55 * math.exp(-d / 0.05) * rng.uniform(0.5, 1.0)
        ch = i % 2
        er[ch, S(d)] += a * (1 if rng.random() > 0.3 else -1)
    er = filt(lp(7000), er)
    return ir + er


def convolve_stereo(x, ir):
    m = 0.5 * (x[0] + x[1])
    yl = fftconvolve(0.7 * x[0] + 0.3 * m, ir[0])[: x.shape[1]]
    yr = fftconvolve(0.7 * x[1] + 0.3 * m, ir[1])[: x.shape[1]]
    return np.vstack([yl, yr])


def sympathetic_ir(rng):
    """Undamped piano strings as a resonator bank (sustain pedal down)."""
    L = int(3.0 * SR)
    t = np.arange(L) / SR
    ir = np.zeros((2, L))
    for m in range(28, 100):
        f = mtof(m)
        for n in range(1, 6):
            fn = n * f
            if fn > 6000:
                break
            tau = 1.6 * 2 ** (-(m - 50) / 24) / n
            ir[m % 2] += (1 / n) * np.sin(TWO_PI * fn * t + rng.random() * 6.3) * np.exp(-t / tau)
    ir *= smoothstep(t / 0.01)
    return ir / np.sqrt(np.sum(ir ** 2) / 2)


# --------------------------------------------------------------------------
# dynamics / mastering
# --------------------------------------------------------------------------
def k_weight(x):
    s1 = np.array([[1.53512485958697, -2.69169618940638, 1.19839281085285,
                    1.0, -1.69065929318241, 0.73248077421585]])
    s2 = np.array([[1.0, -2.0, 1.0, 1.0, -1.99004745483398, 0.99007225036621]])
    return sosfilt(s2, sosfilt(s1, x, axis=-1), axis=-1)


def lufs(x):
    y = k_weight(x)
    blk, hop = int(0.4 * SR), int(0.1 * SR)
    p = np.array([np.mean(y[:, i:i + blk] ** 2, axis=1).sum()
                  for i in range(0, y.shape[1] - blk + 1, hop)])
    lk = -0.691 + 10 * np.log10(p + 1e-20)
    p = p[lk > -70]
    rel = -0.691 + 10 * np.log10(p.mean()) - 10
    p = p[(-0.691 + 10 * np.log10(p)) > rel]
    return -0.691 + 10 * np.log10(p.mean())


def true_peak_db(x):
    up = resample_poly(x, 4, 1, axis=1)
    return 20 * np.log10(np.max(np.abs(up)) + 1e-20)


def compressor(x, thr_db=-20, ratio=2.0, att=0.015, rel=0.2, knee=6.0):
    hop = 48
    n = x.shape[1] // hop
    blk = x[:, : n * hop].reshape(2, n, hop)
    lev = 10 * np.log10(np.mean(blk ** 2, axis=(0, 2)) + 1e-12)
    a_c, r_c = math.exp(-hop / SR / att), math.exp(-hop / SR / rel)
    sm = np.empty(n)
    s = lev[0]
    for i in range(n):
        c = a_c if lev[i] > s else r_c
        s = c * s + (1 - c) * lev[i]
        sm[i] = s
    over = sm - thr_db
    gr = np.where(over <= -knee / 2, 0.0,
                  np.where(over >= knee / 2, over * (1 - 1 / ratio),
                           (1 - 1 / ratio) * (over + knee / 2) ** 2 / (2 * knee)))
    g = 10 ** (-gr / 20)
    gs = np.interp(np.arange(x.shape[1]), np.arange(n) * hop + hop / 2, g)
    return x * gs, float(gr.max())


def soft_clip(x, th=0.7):
    a = np.abs(x)
    y = np.where(a <= th, a, th + (1 - th) * np.tanh((a - th) / (1 - th)))
    return np.sign(x) * y


def limiter(x, ceiling_db=-1.3, look=0.004, rel=0.09):
    c = 10 ** (ceiling_db / 20)
    up = np.abs(resample_poly(x, 4, 1, axis=1)).max(axis=0)
    pk = up[: x.shape[1] * 4].reshape(-1, 4).max(axis=1)
    pk = np.maximum(pk, np.abs(x).max(axis=0))
    need = np.minimum(1.0, c / np.maximum(pk, 1e-9))
    Lk = int(look * SR)
    g1 = minimum_filter1d(need, size=2 * Lk + 1, mode="nearest")
    a = math.exp(-1 / (rel * SR))
    g2 = np.empty_like(g1)
    s = 1.0
    for i, v in enumerate(g1):
        s = v if v < s else a * s + (1 - a) * v
        g2[i] = s
    g3 = uniform_filter1d(g2, size=Lk + 1, mode="nearest")
    return x * g3, float(20 * np.log10(g3.min()))


# --------------------------------------------------------------------------
# the score
# --------------------------------------------------------------------------
def compose():
    # ---- barlines / beats for the picture team
    for b in range(1, 19):
        event("bar", T(b), bar=b)

    # ---- PIANO -------------------------------------------------------------
    def pedal_end(t):          # sustain pedal changes with every chord
        for t0, t1, _ in SEGS:
            if t0 <= t + 1e-9 < t1:
                return t1 + 0.04
        return DUR

    # intro: solo theme, single notes (+ a soft low root on each downbeat)
    for (b, bt, d, n) in THEME:
        t0 = T(b, bt)
        v = 0.42 + (0.08 if bt == 1 else 0) + (0.05 if d >= 1.5 else 0)
        piano(t0, n, v, pedal_end(t0) - t0, record=("melody", {"bar": b, "beat": bt,
              "accent": bt == 1 or d >= 1.5, "section": "intro"}))
    for b in range(1, 5):
        root = M(V[chord_at(T(b))][0]) + 12
        piano(T(b), root, 0.30, BAR, tag="lh")
    # verse: theme answer + left hand root / fifth
    for (b, bt, d, n) in VERSE:
        t0 = T(b, bt)
        v = 0.48 + (0.08 if bt == 1 else 0) + (0.05 if d >= 1.5 else 0)
        piano(t0, n, v, pedal_end(t0) - t0, record=("melody", {"bar": b, "beat": bt,
              "accent": bt == 1 or d >= 1.5, "section": "verse"}))
    for b in range(5, 9):
        c = chord_at(T(b))
        root = M(V[c][0]) + 12
        piano(T(b), root, 0.36, BAR, tag="lh")
        piano(T(b, 3), root + 7, 0.30, BAR / 2, tag="lh")
        piano(T(b, 3), root + 12, 0.26, BAR / 2, tag="lh")

    # build: 8th-note ostinato, register climbing with the harmony
    OST = {9: ["G4", "D5", "B4", "D5"], 10: ["A4", "E5", "C#5", "E5"],
           11: ["B4", "F#5", "D5", "F#5"], 12: ["C#5", "A5", "E5", "A5"]}
    for b in range(9, 13):
        pat = OST[b]
        n8 = 8 if b < 12 else 4                         # bar 12 stops at the hit
        for k in range(n8):
            t0 = T(b) + k * BEAT / 2
            grow = (b - 9) / 3 + k / 32
            v = 0.30 + 0.20 * grow + (0.10 if k % 2 == 0 else 0)
            note = pat[k % 4]
            piano(t0, note, v, BEAT * 0.9, tag="ost", record=("ostinato", {"bar": b}))
            add("pluck", t0, pizz_note(M(note) - 12, 0.55 + 0.35 * grow,
                                       rng_for("pz", round(t0 * 1000))), p=0.35)

    # climax: theme in octaves + harmony, left hand octaves
    for (b, bt, d, n) in CLIMAX:
        t0 = T(b, bt)
        m = M(n)
        accent = bt == 1
        v = 0.72 + (0.12 if accent else 0) + (0.05 if d >= 1.5 else 0)
        hold = pedal_end(t0) - t0
        piano(t0, m + 12, v, hold, tag="cmU", record=("melody", {"bar": b, "beat": bt,
              "accent": True, "section": "climax", "octaves": True}))
        piano(t0, m, v * 0.85, hold, tag="cmL")
        if d >= 1:
            pcs = PCS[chord_at(t0)]
            inner = [x for x in range(m + 2, m + 11) if x % 12 in pcs]
            inner.sort(key=lambda x: abs(x - (m + 6)))
            for i, x in enumerate(inner[:2]):
                piano(t0, x, v * 0.6, hold, tag="cmH")
    for (t0, t1, c) in SEGS:
        if 30 <= t0 < 40:
            root = M(V[c][0])
            piano(t0, root + 12, 0.72, t1 - t0 + 0.05, tag="cmB")
            if t1 - t0 > BEAT * 3:
                tm = t0 + 2 * BEAT
                piano(tm, root + 19, 0.5, t1 - tm, tag="cmB")
                piano(tm, root + 24, 0.45, t1 - tm, tag="cmB")

    # resolve: final D chord at 40.0 (bass + top exact, inner voices rolled)
    final = [("D2", 0.0, 0.62), ("A2", 0.025, 0.45), ("D3", 0.05, 0.45), ("F#3", 0.075, 0.42),
             ("A3", 0.10, 0.42), ("D4", 0.125, 0.45), ("D5", 0.0, 0.6)]
    for n, off, v in final:
        piano(40.0 + off, n, v, 5.0, tag="fin",
              record=("melody", {"bar": 17, "beat": 1, "accent": True, "section": "resolve"})
              if n == "D5" else (("chordRoll", {"bar": 17}) if off > 0 else None))
    piano(T(18), "A4", 0.30, 2.5, tag="echo",
          record=("melody", {"bar": 18, "beat": 1, "accent": False, "section": "resolve"}))
    piano(T(18, 2), "F#5", 0.32, 2.0, tag="echo",
          record=("melody", {"bar": 18, "beat": 2, "accent": False, "section": "resolve"}))

    # ---- PAD (air) --------------------------------------------------------
    for (t0, t1, c) in SEGS:
        if t0 >= DROP - 1.5 and t0 < DROP:          # bar 12 pad stops at the hit
            pass
        bass_n, up = V[c]
        if t0 < 10:
            vel, cut = 0.30, 800
        elif t0 < 20:
            vel, cut = 0.32, 900
        elif t0 < 30:
            vel, cut = 0.30 + 0.03 * (t0 - 20) / 2.5, 1000 + 120 * (t0 - 20) / 2.5
        elif t0 < 40:
            vel, cut = 0.36, 1300
        else:
            vel, cut = 0.34, 850
        end = min(t1, PRE_HIT + 0.1) if t0 < DROP else t1
        dur = end - t0
        if t0 >= 40:
            if t0 > 40:
                continue
            dur = 3.0
        for n in up:
            pad(t0, n, dur + 0.15, vel, cutoff=cut, att=1.2 if t0 > 0 else 1.8,
                rel=1.4 if t0 < 40 else 2.4)
        if t0 >= 30 and t0 < 40:
            pad(t0, up[-1][:-1] + str(int(up[-1][-1]) + 1), dur + 0.15, vel * 0.6, cutoff=cut)

    # ---- STRINGS ----------------------------------------------------------
    for (t0, t1, c) in SEGS:
        bass_n, up = V[c]
        bm = M(bass_n)
        dur = t1 - t0
        if 10 <= t0 < 20:              # verse: low strings enter
            v = 0.36 + 0.04 * (t0 - 10) / 2.5
            strings("cb", t0, bm, dur, v, att=0.6)
            strings("vc", t0, bm + 12, dur, v, att=0.6)
            strings("vla", t0, up[0], dur, v * 0.8, att=0.8)
            strings("vla", t0, up[1], dur, v * 0.8, att=0.8)
        elif 20 <= t0 < 30:            # build: everybody, crescendo, stop at the hit
            v = 0.42 + 0.07 * (t0 - 20) / 2.5
            d = min(dur, PRE_HIT + 0.08 - t0)
            strings("cb", t0, bm, d, v, att=0.35, rel=0.12)
            strings("vc", t0, bm + 12, d, v, att=0.35, rel=0.12)
            strings("vla", t0, up[0], d, v * 0.85, att=0.5, rel=0.12)
            strings("vla", t0, up[1], d, v * 0.85, att=0.5, rel=0.12)
            strings("vln2", t0, up[2], d, v * 0.8, att=0.6, rel=0.12)
        elif 30 <= t0 < 40:            # climax: full section
            v = 0.78
            strings("cb", t0, bm, dur, v, att=0.06, rel=0.6)
            strings("vc", t0, bm + 12, dur, v, att=0.06, rel=0.6)
            strings("vla", t0, up[0], dur, v * 0.85, att=0.12)
            strings("vla", t0, up[1], dur, v * 0.85, att=0.12)
            strings("vln2", t0, up[2], dur, v * 0.8, att=0.12)
            strings("vln2", t0, M(up[2]) + 12, dur, v * 0.55, att=0.15)
    # build: violins I rising line B4 C#5 D5 E5 (tenths over the climbing bass)
    for b, n in zip(range(9, 13), ["B4", "C#5", "D5", "E5"]):
        d = BAR if b < 12 else PRE_HIT + 0.08 - T(b)
        strings("vln1", T(b), n, d, 0.42 + 0.08 * (b - 9), att=0.7 if b == 9 else 0.3, rel=0.12)
    # climax: violins I carry the melody (legato)
    for i, (b, bt, d, n) in enumerate(CLIMAX):
        t0 = T(b, bt)
        strings("vln1", t0, n, d * BEAT + 0.08, 0.72, att=0.07, rel=0.35)
    # resolve: quiet cello/viola D chord under the piano (fades with the pad)
    strings("vc", 40.0, "D3", 2.6, 0.30, att=0.3, rel=1.8)
    strings("vla", 40.0, "A3", 2.6, 0.25, att=0.4, rel=1.8)

    # ---- BRASS (climax) ---------------------------------------------------
    for (t0, t1, c) in SEGS:
        if 30 <= t0 < 40:
            bass_n, up = V[c]
            dur = t1 - t0
            brass(t0, M_name(M(bass_n) + 12), dur, 0.75, p=-0.1)
            brass(t0, up[0], dur, 0.6, p=0.15)
            brass(t0, up[1], dur, 0.55, p=-0.2)

    # ---- SUB / BASS -------------------------------------------------------
    for (t0, t1, c) in SEGS:
        bn = V[c][0]
        if 10 <= t0 < 20:                    # warm pulse on beats 1 & 3
            for k in (0, 2):
                sub(t0 + k * BEAT, bn, BEAT * 1.8, 0.75, decay=0.5, sustain=0.35)
        elif 20 <= t0 < 30:
            beats = (0, 2) if t0 < 25 else (0, 1, 2, 3)
            for k in beats:
                tt = t0 + k * BEAT
                if tt < PRE_HIT:
                    sub(tt, bn, min(BEAT * (1.8 if len(beats) == 2 else 0.9), PRE_HIT + 0.05 - tt),
                        0.8, decay=0.4, sustain=0.35)
        elif 30 <= t0 < 40:
            sub(t0, bn, t1 - t0, 0.95, decay=0.8, sustain=0.6)
    sub(40.0, "D2", 3.5, 0.65, att=0.02, decay=1.2, sustain=0.0, rel=1.0)

    # ---- PERCUSSION -------------------------------------------------------
    # bar 10: toms on 1, 3 and the "and" of 4
    # (all drums are tuned to notes of D major)
    for tt, pitch, v, p in [(T(10, 1), DP("E2"), 0.55, -0.2), (T(10, 3), DP("F#2"), 0.5, 0.2),
                            (T(10, 4.5), DP("A2"), 0.45, 0.3)]:
        hit(tt, "tom", v, pitch, 0.7, p=p)
    # bar 11: every beat + pickup
    for k, tt in enumerate([T(11, 1), T(11, 2), T(11, 3), T(11, 4), T(11, 4.5)]):
        hit(tt, "tom", 0.55 + 0.05 * k, DP(["D2", "F#2", "E2", "A2", "B2"][k]), 0.7, p=[-.3, .25, -.15, .3, .1][k])
    hit(T(11, 1), "taiko", 0.6, DP("B1"), 1.0, p=0.0)
    # bar 12: 16th roll crescendo into the pre-drop hit
    for k in range(8):
        tt = T(12) + k * BEAT / 4
        hit(tt, "tom", 0.45 + 0.06 * k, DP(["E2", "F#2", "A2", "B2"][k % 4]), 0.55, p=-0.35 + 0.1 * k)
    # pre-drop hit (beat 3 of bar 12)
    hit(PRE_HIT, "taiko", 0.95, DP("A1"), 1.3)
    impact(PRE_HIT, "preDropHit", size=0.8, gain=0.8)
    # climax: taiko on every beat, impact on every downbeat
    for k in range(16):
        tt = DROP + k * BEAT
        down = k % 4 == 0
        hit(tt, "taiko", 0.95 if down else 0.72 + 0.04 * (k % 2), bass_hz(tt) / 60.0,
            1.25 if down else 0.9, p=0.0 if down else (-0.15 if k % 2 else 0.15),
            gain=1.0 if down else 0.8)
        if not down:   # light 8th-note ghost on the off-beat for drive
            hit(tt + BEAT / 2, "tomGhost", 0.32, 2 * bass_hz(tt) / 60.0, 0.45, p=0.3 if k % 2 else -0.3,
                gain=0.55, slap=1.4)
    impact(DROP, "DROP", size=1.25, gain=1.1)
    for b in (14, 15, 16):
        impact(T(b), "downbeatImpact", size=0.75, gain=0.55)
    impact(40.0, "resolveBoom", size=0.7, gain=0.28)
    # climax pizz ostinato keeps the 8th-note motion going
    for (t0, t1, c) in SEGS:
        if 30 <= t0 < 40:
            bass_n, up = V[c]
            pat = [M(up[0]) + 12, M(up[2]) + 12, M(up[1]) + 12, M(up[2]) + 12]
            k = 0
            while t0 + k * BEAT / 2 < t1 - 1e-6:
                tt = t0 + k * BEAT / 2
                add("pluck", tt, pizz_note(pat[k % 4], 0.75 + (0.15 if k % 2 == 0 else 0),
                                           rng_for("pzc", round(tt * 1000))), p=0.35)
                k += 1

    # ---- FX ---------------------------------------------------------------
    rr = rng_for("riser")
    rs = riser_sig(PRE_HIT - T(11), rr)
    add("fx", T(11), rs, gain=0.55)
    event("riser", T(11), end=PRE_HIT)
    # reverse cymbal into the pre-drop hit
    cy = cymbal(2.5, rng_for("cy-rev"), decay=1.4)[:, ::-1].copy()
    cy *= np.linspace(0, 1, cy.shape[1]) ** 1.5
    add("fx", PRE_HIT - 2.5, fade_edges(cy, 0.05, 0.002), gain=0.30)
    # DROP: crash + cymbal swell resolving into the downbeat ring
    add("fx", DROP, cymbal(4.5, rng_for("crash"), decay=2.2), gain=0.42)
    event("crash", DROP)
    add("fx", T(15), cymbal(3.5, rng_for("crash2"), decay=1.8), gain=0.22)
    event("crash", T(15))
    # cymbal roll swell into the resolve (bar 16 beats 3-4), soft crash at 40
    sw = cymbal(1.25, rng_for("swell"), decay=1.0)[:, ::-1].copy()
    sw *= np.linspace(0, 1, sw.shape[1]) ** 2
    add("fx", 40.0 - 1.25, fade_edges(sw, 0.05, 0.002), gain=0.20)
    add("fx", 40.0, cymbal(4.0, rng_for("crash3"), decay=2.4), gain=0.14)


def M_name(m):
    names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    return f"{names[m % 12]}{m // 12 - 1}"


# --------------------------------------------------------------------------
# mix & master
# --------------------------------------------------------------------------
GAINS = {"piano": 1.0, "strings": 0.30, "pad": 0.30, "brass": 0.30, "bass": 0.32,
         "perc": 0.52, "impact": 0.42, "fx": 0.35, "pluck": 0.45}
SENDS = {  # (room, hall)
    "piano": (0.30, 0.22), "strings": (0.0, 0.34), "pad": (0.0, 0.30), "brass": (0.0, 0.26),
    "bass": (0.0, 0.0), "perc": (0.10, 0.22), "impact": (0.0, 0.30), "fx": (0.0, 0.25),
    "pluck": (0.18, 0.18),
}
BUS_EQ = {
    "piano": [hp(38), peaking(250, 0.9, -1.5), peaking(3400, 1.4, -1.5)],
    "strings": [peaking(300, 0.8, -1.0), peaking(3000, 1.3, -2.0)],
    "pad": [peaking(280, 0.8, -2.0)],
    "brass": [peaking(220, 0.9, -2.0)],
    "bass": [hp(34, 4), lp(220, 2)],
    "perc": [hp(32), peaking(3000, 1.2, -2.0)],
    "impact": [hp(24), peaking(3000, 1.2, -2.0)],
    "fx": [hp(250), lp(11000, 2)],
    "pluck": [hp(140)],
}


def chorus(x, rng, depth=0.0035, base=0.017, mix=0.45):
    n = np.arange(x.shape[1], dtype=np.float64)
    y = x.copy()
    for ch in range(2):
        for k in range(2):
            r = rng.uniform(0.18, 0.42)
            d = (base + 0.006 * k + depth * np.sin(TWO_PI * r * n / SR + rng.random() * 6.3)) * SR
            y[ch] += mix * 0.5 * np.interp(n - d, n, x[ch], left=0.0)
    return y / (1 + mix * 0.5)


def mixdown():
    rng = rng_for("mix")
    room_ir = make_ir(1.1, 2.2, 0.012, rng_for("room"), n_er=12, er_span=0.035)
    hall_ir = make_ir(2.5, 4.5, 0.024, rng_for("hall"), n_er=16, er_span=0.08)
    sym_ir = sympathetic_ir(rng_for("sym"))
    # piano: sustain-pedal sympathetic resonance
    bus["piano"] += 0.06 * convolve_stereo(filt(hp(120), bus["piano"]), sym_ir)
    bus["strings"] = chorus(bus["strings"], rng_for("ch-str"))
    bus["pad"] = chorus(bus["pad"], rng_for("ch-pad"), depth=0.005, mix=0.6)
    dry = np.zeros((2, NT))
    room_send = np.zeros((2, NT))
    hall_send = np.zeros((2, NT))
    # sidechain: sub/bass ducks under taiko + impacts (keeps the low end from stacking)
    kick = filt(lp(150), (bus["perc"] + bus["impact"]).sum(0))
    env = np.sqrt(uniform_filter1d(kick ** 2, size=int(0.01 * SR)))
    env = env / (env.max() + 1e-12)
    a_r = math.exp(-1 / (0.30 * SR))
    hop = 48
    e = env[::hop]
    sm = np.empty_like(e)
    s = 0.0
    for i, v in enumerate(e):
        s = v if v > s else a_r ** hop * s + (1 - a_r ** hop) * v
        sm[i] = s
    duck = 10 ** (-3.5 * np.clip(sm / 0.35, 0, 1) / 20)       # up to -3.5 dB
    bus["bass"] *= np.interp(np.arange(NT), np.arange(len(e)) * hop, duck)
    for k in BUSES:
        x = bus[k]
        for sos in BUS_EQ[k]:
            x = filt(sos, x)
        x = x * GAINS[k]
        dry += x
        room_send += SENDS[k][0] * x
        hall_send += SENDS[k][1] * x
    pre = [hp(200), lp(9000)]
    for sos in pre:
        room_send = filt(sos, room_send)
        hall_send = filt(sos, hall_send)
    wet = 0.55 * convolve_stereo(room_send, room_ir) + 0.62 * convolve_stereo(hall_send, hall_ir)
    mix = dry + wet
    mix = filt(hp(22, 2), mix)
    return mix[:, :N].copy()


def master(mix):
    t = np.arange(N) / SR
    # gentle glue
    mix, gr = compressor(mix, thr_db=-16, ratio=1.6, att=0.02, rel=0.25)
    # pre-drop vacuum: everything (incl. reverb tails) closes 28.86-28.93,
    # reopens exactly at the DROP (no sound before 30.000 except the swell)
    g = np.ones(N)
    a, b = S(GATE_FROM), S(GATE_TO)
    g[a:b] = 0.5 + 0.5 * np.cos(np.pi * np.arange(b - a) / (b - a))
    g[b:S(DROP)] = 0.0
    mix = mix * g
    # very quiet reverse swell sucked into the DROP (added after the gate)
    sw = cymbal(0.9, rng_for("vac"), decay=0.6)[:, ::-1].copy()
    sw *= np.linspace(0, 1, sw.shape[1]) ** 3
    sw = fade_edges(filt(hp(1500), sw), 0.1, 0.003)
    mix[:, S(DROP) - sw.shape[1]:S(DROP)] += 0.006 * sw
    # final fade to true digital silence at 45.000
    f0 = S(42.4)
    fade = np.ones(N)
    fade[f0:] = (0.5 + 0.5 * np.cos(np.pi * np.arange(N - f0) / (N - f0))) ** 1.3
    mix *= fade

    # loudness to -14 LUFS with soft clip + true-peak limiter (iterate)
    gain_db = -14.0 - lufs(mix)
    for _ in range(5):
        y = soft_clip(mix * 10 ** (gain_db / 20) / 10 ** (-1.3 / 20) * 0.98, 0.72) * 10 ** (-1.3 / 20) / 0.98
        y, lim = limiter(y, -1.3)
        L = lufs(y)
        if abs(L + 14.0) < 0.05:
            break
        gain_db += -14.0 - L
    y[:, -1] = 0.0
    return y, {"lufs_internal": L, "truepeak_internal": true_peak_db(y), "limiter_max_gr_db": lim,
               "comp_max_gr_db": gr, "gain_db": gain_db}


def export_markers(path):
    ev = sorted(EVENTS, key=lambda e: (e["t"], e["type"]))
    beats = [{"beat": k, "t": round(k * BEAT, 6), "sample": k * 30000,
              "bar": k // 4 + 1, "beatInBar": k % 4 + 1} for k in range(72)]
    out = {
        "source": "audio/bears-brand-score-45s.wav",
        "generator": "audio/compose.py (events exported directly from the score)",
        "seed": SEED, "sampleRate": SR, "bpm": BPM, "beat": BEAT, "bar": BAR,
        "duration": DUR, "key": "D major",
        "barlines": [{"bar": b, "t": round(T(b), 6), "sample": S(T(b)),
                      "chord": chord_at(T(b))} for b in range(1, 19)] + [
            {"bar": 19, "t": DUR, "sample": N, "chord": None, "note": "end"}],
        "beats": beats,
        "chords": [{"t": round(a, 6), "until": round(b, 6), "chord": c.replace("*", "")}
                   for a, b, c in SEGS],
        "impacts": [e for e in ev if e["type"] in ("preDropHit", "DROP", "downbeatImpact", "resolveBoom")],
        "hits": [e for e in ev if e["type"] in ("taiko", "tom", "tomGhost", "crash")],
        "melody": [e for e in ev if e["type"] == "melody"],
        "melodyAccents": [e for e in ev if e["type"] == "melody" and e.get("accent")],
        "ostinato": [e for e in ev if e["type"] == "ostinato"],
        "chordRoll": [e for e in ev if e["type"] == "chordRoll"],
        "fx": {"riser": {"from": T(11), "to": PRE_HIT},
               "vacuum": {"from": GATE_FROM, "silentFrom": GATE_TO, "to": DROP},
               "fadeOut": {"from": 42.4, "to": DUR}},
        "sections": CONTRACT["sections"],
    }
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, ensure_ascii=False, indent=1)


def main():
    t_start = time.time()
    problems = check_voice_leading()
    print("voice leading:", "no parallel 5ths/8ves" if not problems else problems)
    compose()
    print(f"composed {len(EVENTS)} events in {time.time() - t_start:.1f}s")
    mix = mixdown()
    y, info = master(mix)
    print("master:", {k: round(v, 2) for k, v in info.items()})
    assert y.shape == (2, N)
    wav = os.path.join(HERE, "bears-brand-score-45s.wav")
    wavfile.write(wav, SR, y.T.astype(np.float32))
    export_markers(os.path.join(HERE, "brand-score-markers.json"))
    ff = shutil.which("ffmpeg")
    if ff:
        subprocess.run([ff, "-y", "-v", "error", "-i", wav, "-c:a", "libmp3lame", "-b:a", "320k",
                        "-metadata", "title=BEARS FANTASY LAND brand score 45s",
                        "-metadata", "artist=BEARS FANTASY LAND (in-house synthesis)",
                        os.path.join(HERE, "bears-brand-score-45s.mp3")], check=True)
    else:
        print("ffmpeg not found: MP3 skipped", file=sys.stderr)
    print(f"done in {time.time() - t_start:.1f}s")


if __name__ == "__main__":
    main()
